aws/homebrew-tap

- Formula/aws-sam-cli.rb
> SAM CLI release v0.12.0

- Formula/aws-sam-cli.rb
> chore: v0.13.0 Release

- Formula/aws-sam-cli.rb
> chore: aws sam cli v0.14.0 release

- Formula/aws-sam-cli.rb
> chore: aws sam cli v0.14.1 release

- Formula/aws-sam-cli.rb
> chore: v0.14.2 aws-sam-cli release

- Formula/aws-sam-cli.rb
> chore(version): 0.15.0 release

- Formula/aws-sam-cli.rb
> chore(version): v0.16.0

- Formula/aws-sam-cli.rb
> feat(bottles): add bottles for mac and linux

- Formula/aws-sam-cli.rb
> chore(0.16.1): Update formula with 0.16.1 source

- Formula/aws-sam-cli.rb
> chore(bottles): Add bottles for 0.16.1 release

- Formula/aws-sam-cli.rb
> chore: v0.18.0 release

- Formula/aws-sam-cli.rb
Artifacts at: https://github.com/awslabs/aws-sam-cli/releases/tag/v0.18.0
> chore: v0.18.0 mac and linux bottles

- Formula/aws-sam-cli.rb
> chore: release v0.19.0

- Formula/aws-sam-cli.rb
> chore: v0.19.0 mac and linux bottles

- .travis.yml
- on master commits build bottles and push it to s3 per commit.
> feat: travis builds mac os x bottles

- .travis.yml
> fix: bottle building branch to be `master`

- .travis.yml
> feat: bottle building for mac

- Formula/aws-sam-cli.rb
> chore: Update tap to use v0.22 SAM CLI

- Formula/aws-sam-cli.rb
> Update bottles for v0.22.0 SAM CLI

- Formula/aws-sam-cli.rb
> chore: Update url to v0.23.0 link

- Formula/aws-sam-cli.rb
> chore: Updated with v0.23.0 Bottles

- Formula/aws-sam-cli.rb
> fix: root_url link for 0.23.0

- Formula/aws-sam-cli.rb
> chore: 0.30.0 Python Package

- Formula/aws-sam-cli.rb
> v0.30.0: Add New Brew Tap Info

- Formula/aws-sam-cli.rb
> chore: SAM CLI Release v0.31.0

- Formula/aws-sam-cli.rb
> chore: Updating bottles for SAM CLI v0.31.0

- Formula/aws-sam-cli.rb
> chore: SAM CLI Release v0.31.1

- Formula/aws-sam-cli.rb
> chore: Updating bottles for SAM CLI v0.31.1

- Formula/aws-sam-cli.rb
> chore: SAM CLI Release v0.32.0

- Formula/aws-sam-cli.rb
> chore: Updating bottles for SAM CLI v0.32.0

- Formula/aws-sam-cli.rb
> chore: SAM CLI Release v0.33.0

- Formula/aws-sam-cli.rb
This reverts commit bd41dfa41e1f2466cc286185e6ef1f3605a9b924.
> Revert "chore: SAM CLI Release v0.33.0 (#56)"

- Formula/aws-sam-cli.rb
> fix: bottles with pip pinned

- Formula/aws-sam-cli.rb
> chore: SAM CLI Release v0.33.1

- Formula/aws-sam-cli.rb
> chore: Updating bottles for SAM CLI v0.33.1

- Formula/aws-sam-cli.rb
> chore: Updating bottles for SAM CLI v0.34.0

- Formula/aws-sam-cli.rb
> chore: Updating bottles to SAM CLI v0.34.0

- Formula/aws-sam-cli.rb
> chore: Updating to SAM CLI v0.35.0

- Formula/aws-sam-cli.rb
> chore: Updating bottles to SAM CLI v0.35.0

- Formula/aws-sam-cli.rb
> chore: Bumping to SAM CLI v0.36.0

- Formula/aws-sam-cli.rb
> chore: update bottle for v0.36.0

- Formula/aws-sam-cli.rb
> chore: version bump to v0.37.0

- Formula/aws-sam-cli.rb
> chore: bottles for 0.37.0 aws-sam-cli

- Formula/aws-sam-cli.rb
- Formula/config-provider.rb
- Formula/config_provider.rb
- bottle-config.json
- build-bottles.sh
*Purpose*
As goal towards fully automated releases, this PR is to move hardcoded values to a config.json file. This will make it easy to programmatically update these values.
*Testing*
Pulled the code change in local homebrew repo and modified hashes and values to install 0.36.0. On running `brew install aws-sam-cli` version 0.36.0 was installed.
```
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.36.0//aws-sam-cli-0.36.0.sierra.bottle.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/92205085/393cb880-15eb-11ea-82d3-87db0a82f839?X-Amz-Algor …
```
> Refactor to json

- bottle-config.json
> chore: version bump to v0.38.0

- bottle-config.json
> chore: bottles for 0.38.0 aws-sam-cli

- bottle-config.json
> chore(version): 0.39.0 release

- bottle-config.json
> Add Bottle Configuration

- bottle-config.json
This reverts commit 67c6069b379e4f07ff8fdcf6030432ff5e49b487.
> Revert "chore: version bump to 0.42.0"

- Formula/aws-sam-cli.rb
Updates the Python version used by AWS SAM CLI 
> update python package in SAM to python3.8

- Formula/aws-sam-cli.rb
We are not making this change yet, due to release issues.
> Revert "update python package in SAM to python3.8"

- bottle-config-rc.json
> RC1 Bottle Build in Progress

- bottle-config-rc.json
> AWS SAM CLI RC Formula for 1.0.0rc1

- Formula/aws-sam-cli-rc.rb
- Formula/aws-sam-cli.rb
> Switch python version to be python3.7 for sam cli formulas

- Formula/aws-sam-cli-rc.rb
- Formula/aws-sam-cli.rb
> Revert "Switch python version to be python3.7 for sam cli formulas"

- bottle-configs/aws-sam-cli-rc.json
> chore: sam cli version to rc2

- Formula/aws-sam-cli-rc.rb
> Update python depends on to python3.7

- Formula/aws-sam-cli-rc.rb
> Fix: replace dependson:python3.7 with python@3.7

- bottle-configs/aws-sam-cli-rc.json
- build-formula.sh
> Fix rc2 sha and allow homebrew to update on mac

- build-formula.sh
> Force brew update in build bottles

- bottle-configs/aws-sam-cli-rc.json
> Update bottle shas for SAM CLI rc2

- Formula/aws-sam-cli.rb
> Pin aws-sam-cli formula to python3.7

- bottle-configs/aws-sam-cli.json
> Fix 0.53.0 bottles for SAM CLI

- bottle-configs/copilot-cli.json
> Update Linux binary sha

- Formula/ec2-metadata-mock.rb
- bottle-configs/ec2-metadata-mock.json
N/A
- Use static binaries for ec2-metadata-mock 
> aemm to static bottle

- bottle-configs/aws-sam-cli.json
> Update AWS SAM CLI Formula

- bottle-configs/copilot-cli.json
https://github.com/aws/copilot-cli/releases/tag/v0.3.0
> Upgrade copilot to v0.3.0 🥂

- bottle-configs/copilot-cli.json
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> update Copilot binary to v0.4.0

- bottle-configs/aws-sam-cli.json
> Revert aws-sam-cli to 1.3.0

- Formula/aws-sam-cli.rb
> Fixing broken bottle building due to latest homebrew change.

- Formula/aws-sam-cli.rb
> Put pip installation back

- bottle-configs/aws-sam-cli.json
> rollback sam cli 1.4.0

- Formula/aws-sam-cli.rb
> rollback python version to 3.7 for sam cli

- Formula/aws-sam-cli.rb
- bottle-configs/aws-sam-cli.json
> chore: bumping version to 1.6.2

- bottle-configs/copilot-cli.json
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> chore(copilot): bump version to v0.5.0

- bottle-configs/copilot-cli.json
> chore: bump copilot cli to v0.6.0

- bottle-configs/copilot-cli.json
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> chore: upgrade copilot cli to v0.7.0

- bottle-configs/copilot-cli.json
> chore: update copilot to v1.0.0

- bottle-configs/aws-sam-cli.json
This reverts commit 1201a66d0a6ada5ad9d34415ae4260a129c77305.
> Revert "chore: version bump to 1.13.0"

- Formula/copilot-cli.rb
I can now see suggestions once I press tab:
> fix: completion of commands for copilot

- Formula/aws-simple-ec2-cli.rb
- bottle-configs/aws-simple-ec2-cli.json
*Issue #, if available:* Add [AWS Simple EC2 CLI ](https://github.com/awslabs/aws-simple-ec2-cli) formula
> Add aws-simple-ec2-cli formula

- README.md
> Add aws-simple-ec2 to README

- bottle-configs/aws-sam-cli.json
> fix: update homebrew hashes

- bottle-configs/copilot-cli.json
> chore: ugprade copilot to v1.2.0

- Formula/lightsailctl.rb
- README.md
- bottle-configs/lightsailctl.json
*Description of changes:* add the formula for `lightsailctl`
> Add lightsailctl formula

- bottle-configs/copilot-cli.json
> chore: bump aws copilot cli to v1.3.0

- bottle-configs/aws-sam-cli.json
This reverts commit f93ba7d804ce1844286bf243f3a5a44fb9964996.
> Revert "chore: version bump to 1.20.0"

- bottle-configs/copilot-cli.json
> chore: update Copilot v1.4.0

- Formula/aws-sam-cli-nightly.rb
- bottle-configs/appveyor-nightly-build.yml
- bottle-configs/aws-sam-cli-nightly.json
- build-formula.sh
> homebrew configs for nightly builds

- appveyor-sam-cli-nightly.yml
> Add new appveyor proj to build brew bottles

- Formula/qldbshell.rb
- bottle-configs/qldbshell.json
Previously this Formula only worked on Mac. With this change it works on Linux too. See https://github.com/alpian/repro-brew-tap-aws/runs/2239889870?check_suite_focus=true for evidence.
> Add support for Linux

- bottle-configs/copilot-cli.json
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> chore: update copilot-cli to v1.5.0

- bottle-configs/aws-sam-cli.json
This reverts commit a42bc2b2734802a3f664c147d409468328e4552e.
> Revert "chore: version bump to 1.23.0"

- build-formula.sh
> Removed installing perl from rename

- bottle-configs/copilot-cli.json
> chore: update copilot-cli to v1.6.0

- README.md
- bottle-configs/qldbshell.json
Update the bottle config for v2.0.0-alpha9 of the QLDB Shell. Also update the README.md of this package to include QLDB Shell.
> Release v2.0.0-alpha9 of the QLDB Shell

- bottle-configs/qldbshell.json
> Release v2.0.0-alpha10 of the QLDB Shell

- bottle-configs/copilot-cli.json
> chore: upgrade copilot to v1.7.0

- bottle-configs/copilot-cli.json
> chore: upgrade copilot cli to v1.7.1

- Formula/k8s-tools.rb
- README.md
Adds a k8s-tools meta package to compliment the container-tools package.
> Add k8s-tools meta package

- Formula/k8s-tools.rb
Fix for conflicting class name
> Rename k8s-tools class

- bottle-configs/copilot-cli.json
> chore: upgrade copilot to v1.8.0

- bottle-configs/copilot-cli.json
> chore: upgrade copilot to v1.8.1

- bottle-configs/copilot-cli.json
> chore: upgrade copilot to v1.8.2

- bottle-configs/copilot-cli.json
> chore: upgrade copilot to v1.8.3

- bottle-configs/copilot-cli.json
> chore: upgrade copilot-cli to version v1.9.0

- Formula/ec2-instance-selector.rb
N/A
Support apple silicon arm64 
> instance-selectors mac arm64 support

- Formula/ec2-instance-selector.rb
N/A
small typo in ec2-instance-selector formula
> fix typo in ec2-instance-selector formula

- bottle-configs/copilot-cli.json
> chore: upgrade copilot-cli to v1.10.0

- bottle-configs/copilot-cli.json
> chore: upgrade copilot-cli to v1.10.1

- Formula/eks-anywhere.rb
- README.md
> chore: add eks-anywhere formula

- Formula/eks-anywhere.rb
> chore: fix eks-anywhere shas

- Formula/eks-anywhere.rb
> chore: update deps for eks-anywhere

- Formula/copilot-cli.rb
- bottle-configs/copilot-cli.json
> chore: add macOS arm64 support for copilot-cli

- bottle-configs/copilot-cli.json
> chore: add "linux_arm" option to copilot-cli bottle config

- bottle-configs/aws-sam-cli.json
This reverts commit 04028fc1f6fcd03275b22752b90d0422848f530e.
> Revert "chore: version bump to 1.32.0"

- Formula/emr-on-eks-custom-image.rb
- README.md
- bottle-configs/amazon-emr-on-eks-custom-image-cli.json
Added brew formula and config file for [amazon-emr-on-eks-custom-image-cli](https://github.com/awslabs/amazon-emr-on-eks-custom-image-cli), also updated ReadMe with custom image cli repo details. EMR on EKS custom image cli enables customers to interact with EMR on EKS custom images via a CLI tool.
> Added EMR on EKS Custom Image CLI

- Formula/aws-sam-cli-beta-acc.rb
- appveyor-sam-cli-beta-acc.yml
- bottle-configs/aws-sam-cli-beta-acc.json
> Add beta accelerate basic configs

- bottle-configs/copilot-cli.json
> fix: version of copilot-cli v1.11.0

- Formula/eks-anywhere.rb
https://github.com/aws/eks-anywhere/issues/118
Update eks-anywhere formula for v0.6.0
> Update eks-anywhere formula for v0.6.0

- Formula/eks-anywhere.rb
Bump up EKSA version for v0.6.1
> chore: bump up EKSA version for v0.6.1

- appveyor-sam-cli-nightly.yml
> ci: update appveyor images

- Formula/litani.rb
- README.md
Added a brew formula to install [Litani](https://github.com/awslabs/aws-build-accumulator)
> Add litani-1.19.0 (aws-build-accumulator) formula

- .gitignore
- appveyor.yml
- build-formula.sh
- replace-local-tap.sh
- update-local-tap.sh
N/A
Adding support for building bottles with local files instead of remote tap.
Files of this repo will be copied into homebrew's tap directory and tricking it for bottle building.
> feat: Adding Support for Local Tap

- Formula/litani.rb
> Update Litani formula to follow homebrew-core's best practices

- Formula/litani.rb
- README.md
> Fix: litani doc lib issue

- Formula/litani.rb
Replace url and sha with tag and revision
Remove voluptuous dependency
> Replace url and sha with tag and revision

- Formula/cbmc-viewer.rb
- README.md
> Add cbmc-viewer 2.10 formula

- Formula/cbmc-viewer.rb
> Add test to cbmc-viewer formula

- Formula/cbmc-viewer.rb
> Fix: remove assert from cbmc-viewer test

- bottle-configs/qldbshell.json
https://github.com/awslabs/amazon-qldb-shell/releases/tag/v2.0.1
> Release qldbshell v2.0.1

- Formula/cbmc-viewer.rb
> fix: minor syntax bug in cbmc-viewer.rb

- Formula/cbmc-viewer.rb
> Update cbmc-viewer test

- bottle-configs/aws-sam-cli.json
> Revert "chore: SAM CLI Release 1.41.0"

- Formula/eks-anywhere.rb
Update EKS Anywhere formula to point at our latest release.
> Update eks-anywhere formula for v0.8.1

- Formula/cbmc-starter-kit.rb
> Add cbmc-starter-kit 1.0 brew formula

- Formula/cbmc-starter-kit.rb
> Update homepage of cbmc-starter-kit

- Formula/cbmc-starter-kit.rb
> Bump cbmc-starter-kit to 2.0

- Formula/cbmc-starter-kit.rb
> Update cbmc-starter-kit formula with tag and revision

- Formula/cbmc-starter-kit.rb
> Update cbmc-starter-kit test

- Formula/eks-anywhere.rb
Update EKS Anywhere formula to point at our latest release.
> Update eks-anywhere formula for v0.8.2

- bottle-configs/amazon-emr-on-eks-custom-image-cli.json
Updated the version to 1.02 for EMR on EKS custom image cli.
Last updated commit: https://github.com/aws/homebrew-tap/pull/258/commits/1da2002bf9c575e532fea34d9b199be6e9708acf
> Update EMR on EKS custom image cli to v1.02

- Formula/cbmc-starter-kit.rb
This add bash completion to cbmc-starter-kit.
> Add bash completion to cbmc-starter-kit

- Formula/cbmc-viewer.rb
This add bash completion to cbmc-viewer.
> Add bash completions to cbmc-viewer

- Formula/cbmc-starter-kit.rb
> Correct cbmc-starter-kit base completion installation.

- Formula/cbmc-viewer.rb
> Correct cbmc-viewer bash completion installation.

- Formula/ec2-spot-interrupter.rb
N/A
update ec2-spot-interrupter to v0.0.4
> update ec2-spot-interrupter to v0.0.4

- Formula/ec2-spot-interrupter.rb
N/A
- Upgrade ec2-spot-interrupter to v0.0.5
> upgrade ec2-spot-interrupter to v0.0.5

- Formula/ec2-spot-interrupter.rb
N/A
- Fix ec2-spot-interrupter checksums
> fix ec2-spot-interrupter checksums

- bottle-configs/aws-simple-ec2-cli.json
* Upgrade to go 1.18 by @snay2 in https://github.com/awslabs/aws-simple-ec2-cli/pull/66
* Upgrade dependencies by @snay2 in https://github.com/awslabs/aws-simple-ec2-cli/pull/67
* End-to-end tests by @snay2 in https://github.com/awslabs/aws-simple-ec2-cli/pull/68
* Validation fix if user enters invalid input by @LikithaVemulapalli in https://github.com/awslabs/aws-simple-ec2-cli/pull/71
* @LikithaVemulapalli made their first contribution in https://github.com/awslabs/aws-simple-ec2-cli/pull/71
**Full Changelog**: https://github.com/awslabs/aws-simple-ec2-cli/compare/v0.8.0...v0.8.1
> simple-ec2 v0.8.1 Automated Release!

- bottle-configs/amazon-emr-on-eks-custom-image-cli.json
*Description of changes:* Update emr on eks custom image cli to v1.03. Tested locally.
> Update emr on eks custom image cli to v1.03

- appveyor.yml
> fix: use previous appveyor image

- appveyor.yml
> Revert "fix: use previous appveyor image"

- appveyor.yml
> fix: use previous image for ubuntu

- appveyor.yml
> update with master

- appveyor.yml
> chore: use ubuntu2004 image and setup shh conn

- appveyor.yml
> merge master back to sam cli release

- appveyor.yml
> fix: mitigate homebrew 3.6.0 issue

- appveyor.yml
> fix: add missing -y flag

- appveyor.yml
> merge master

- ConfigProvider/config_provider.rb
- Formula/aws-sam-cli-nightly.rb
- appveyor-sam-cli-nightly.yml
- bottle-configs/aws-sam-cli-nightly.json
The following changes update the linux bottle config and formula for aws-sam-cli-nightly
> Update linux formula and bottle config for aws-sam-cli nightly 

- Formula/aws-sam-cli-nightly.rb
- bottle-configs/aws-sam-cli-nightly.json
Fixing the nightly formula class that calls the is_native_binary_supported function and updating the bottle config for nightly build.
> fix: Fixed sam-cli-nightly build error

- Formula/aws-sam-cli.rb
- appveyor.yml
- bottle-configs/aws-sam-cli.json
N/A
The following changes update the linux bottle config and formula for aws-sam-cli
> Updated sam cli linux bottle config and formula

- bottle-configs/qldbshell.json
https://github.com/awslabs/amazon-qldb-shell/releases/tag/v2.0.2
> Release qldbshell v2.0.2

- Formula/cbmc-starter-kit.rb
- Formula/cbmc-viewer.rb
> Bump python version to 3.10 for cbmc-starter-kit

- Formula/ec2-spot-interrupter.rb
*Description of changes:* 
- ec2-spot-interrupter: v0.0.10 https://github.com/aws/amazon-ec2-spot-interrupter/releases/tag/v0.0.10
> ec2-spot-interrupter: v0.0.10

- Formula/aws-ddbsh.rb
- README.md
Add [dynamodb-shell](https://github.com/awslabs/dynamodb-shell) to the AWS tap
> aws-ddbsh 0.2

- Formula/ec2-spot-interrupter.rb
https://github.com/aws/amazon-ec2-spot-interrupter/issues/58
- Fix bad checksums :( 
> ec2-spot-interrupter: fix checksums

- Formula/aws-ddbsh.rb
Update [dynamodb-shell](https://github.com/awslabs/dynamodb-shell) to v0.3
> ddbsh v0.3

- Formula/aws-ddbsh.rb
Update [dynamodb-shell](https://github.com/awslabs/dynamodb-shell) to v0.4
> aws-ddbsh 0.4

- Formula/aws-ddbsh.rb
Retagged the branch and the hash changed.
Needed to correct the tag for v0.4.
> Update aws-ddbsh.rb for version 0.4.

- Formula/aws-ddbsh.rb
ddbsh version 0.5 is hash 1bd94509d88ded385e9907fc35c1e806b3b86ccb
> ddbsh v0.5

- Formula/eksdemo.rb
- README.md
> add eksdemo formula

- bottle-configs/aws-sam-cli.json
> Sam cli release

- Formula/eks-node-viewer.rb
- README.md
- bottle-configs/eks-node-viewer.json
> add eks-node-viewer

- Formula/eksdemo.rb
Update `eksdemo` brew formula for v0.8.0
> update eksdemo brew formula for v0.8.0

- bottle-configs/eks-node-viewer.json
Updates to latest eks-node-viewer
> update to v0.4.1

- Formula/eksdemo.rb
Update `eksdemo` brew formula for v0.9.0
> update eksdemo brew formula for v0.9.0

- Formula/aws-sam-cli.rb
> Revert "fix: Added workaround to address cython breaking PyYAML build"

- bottle-configs/eks-node-viewer.json
Updates to the latest eks-node-viewer release
> update eks-node-viewer to v0.4.2

- bottle-configs/eks-node-viewer.json
> Fix the eks-node-viewer URL

- bottle-configs/eks-node-viewer.json
Updates to the latest eks-node-viewer version
> upgrade to v0.5.0 of eks-node-viewer

- Formula/eks-anywhere.rb
Update EKS Anywhere formula to point at our latest release.
> Update eks-anywhere brew formula for v0.18.0

- bottle-configs/eks-node-viewer.json
N/A
Release EKS Node Viewer v0.6.0
> eks-node-viewer - v0.6.0 release

- Formula/cbmc-starter-kit.rb
`brew audit` complains: `* line 13, col 52: Align bottle digests`
> cbmc-starter-kit: address `brew audit` warning

- bottle-configs/eks-node-viewer.json
update to the latest eks-node-viewer
> update to the latest eks-node-viewer

- bottle-configs/amazon-emr-on-eks-custom-image-cli.json
Updated the version to 1.06 for EMR on EKS custom image cli.
> Update EMR on EKS custom image cli to v1.06

- bottle-configs/eks-node-viewer.json
> update to eks-node-viewer v0.7.1

- Formula/eks-anywhere.rb
Issue #, if available:
Description of changes:
Update EKS Anywhere formula to point at our latest release.
> chore: update eks-anywhere formula for v0.21.4

- bottle-configs/eks-node-viewer.json
update eks-node-viewer to v0.7.4
> update eks-node-viewer to v0.7.4

- Formula/eks-auto-mode-ebs-migration-tool.rb
- README.md
- bottle-configs/eks-auto-mode-ebs-migration-tool.json
Add the eks-auto-mode-ebs-migration-tool formula
> add the eks-auto-mode-ebs-migration-tool formula

- bottle-configs/eks-auto-mode-ebs-migration-tool.json
Update eks-auto-mode-ebs-migration-tool to v0.4.0
> eks-auto-mode-ebs-migration-tool: update to v0.4.0

- bottle-configs/eks-auto-mode-ebs-migration-tool.json
update the EKS Auto Mode EBS Migration tool to v0.5.1
> update the EKS Auto Mode EBS Migration tool to v0.5.1
