Formula/aws-sam-cli.rb

- This blocks creation of bottles if not removed.

rm(flag): remove bottles being un-needed

---

Formula/aws-sam-cli.rb

chore(version): 0.17.0 release

---

appveyor.yml

This change improves bottle building time on appveyor from 10+ mins to 3 mins. Please check [sample project](https://ci.appveyor.com/project/c2tarun/homebrew-tap) for build time.
We were using Linuxbrew's alternative install method, which was compiling all the dependencies for linuxbrew. This was taking lot of time and our bottle building for linux was taking around 10 mins. This changes replaces alternative install method with install script supported by linux brew.

Installing linuxbrew with install script to speed up linux bottle building process.

---

bottle-config.json

This reverts commit 48d1ebfc554e5ce269cfd4392d6c68a6c2ea6e07.
Reverting as we are dealing with build issues.

Revert "chore: version bump to 0.49.0"

---

ConfigProvider/config_provider.rb
Formula/aws-sam-cli-rc.rb
bottle-config-rc.json

This seems to cover our bases with config providers and bottle builders. The config files align for now but for the rc1 release they should diverge.

Add aws-sam-cli-rc Formula

---

Formula/aws-sam-cli-rc.rb

Error below
```
==> Tapping aws/tap
Cloning into '/usr/local/Homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 455 (delta 31), reused 21 (delta 11), pack-reused 398
Receiving objects: 100% (455/455), 92.56 KiB | 3.19 MiB/s, done.
Resolving deltas: 100% (186/186), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-rc.rb
No available formula with the name "aws-sam-cli-rc"
In formula file: /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-rc.rb
Expected to find class AwsSamCliRc, but only found: AwsSamCli.
Error: Cannot tap aws/tap: invalid syntax in tap!
```
By submitting this pull …

fix: Correct class name on aws sam cli rc formula

---

Formula/ec2-instance-selector.rb
Formula/ec2-metadata-mock.rb

N/A
Use GOPROXY=direct on go builds so that the google module proxy is not required. 

set GOPROXY to direct

---

Formula/copilot-cli.rb
README.md
bottle-configs/copilot-cli.json

Copilot is a new CLI from the ECS Developer Experience team
to make developing, releasing and operating container apps on
AWS delightful.
This PR is to add Copilot to the AWS tap. Since our CLI is vended
as static binaries, we can skip the build step and use our pre-built
binaries which are produced as part of our release pipeline.
Right now we have binaries for MacOS and Intel Linux (ARM to come).
We also install shell autocompletion when installed from the tap.
Thanks so much for hosting this tap!

Add AWS Copilot Formula 🍾

---

ConfigProvider/config_provider.rb
Formula/ec2-instance-selector.rb
bottle-configs/ec2-instance-selector.json
build-bottles.sh
build-formula.sh

N/A
- Move to use static bottles vended from the ec2-instance-selector github releases.
- Modified `build-formula` to skip bottle building when `bottle :unneeded` is specified in the formula.

ec2-instance-selector: static bottles

---

bottle-configs/copilot-cli.json

https://github.com/aws/copilot-cli/releases/tag/v0.2.0

Bump Copilot CLI version to v.0.2.0

---

appveyor.yml

Building only aws-sam-cli when using SAM's appveyor build.

Building only sam-cli when building on appveyor.

---

Formula/xray-daemon.rb
README.md
bottle-configs/xray-daemon.json

https://github.com/aws/homebrew-tap/issues/83
https://github.com/aws/aws-xray-daemon/issues/57
- Add formula for the aws-xray-daemon
Tested on forked tap:
```
$ brew tap bwagner5/tap
$ brew install bwagner5/tap/xray-daemon
$ xray-daemon --help
Usage: X-Ray [options]
-a	--resource-arn	Amazon Resource Name (ARN) of the AWS resource running the daemon.
-o	--local-mode	Don't check for EC2 instance metadata.
-m	--buffer-memory	Change the amount of memory in MB that buffers can use (minimum 3).
-n	--region	Send segments to X-Ray service in a specific region.
-b	--bind		Overrides default UDP address (127.0.0.1:2000).
-t	--bind-tcp	Overrides default TCP address (127.0.0.1:2000).
-r	--role-arn	Assume the specified IAM role to upload segments to a …
```

xray daemon

---

bottle-configs/copilot-cli.json

The linux binary wasn't correct - so updating the sha to the correct
file.

update Copilot linux binary SHA

---

Formula/container-tools.rb
README.md

Adds a new formula for common AWS container tools in 1 package
`brew install aws/tap/container-tools` will install (if not already installed)
- awscli
- kubectl
- copilot
- docker ecr helper (used for docker push/pull)
- aws iam authenticator (used for kubectl auth)
Also added a description to the readme for users to get a quick glance at formula without clicking out to external repos

Add a meta formula for "container tools"

---

Formula/aws-sam-cli.rb

*Issue:*
pip version lock causes issues when creating new brew bottles for `aws-sam-cli`.
```
File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
abstract_dist = self._get_abstract_dist_for(req_to_install)
File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 305, in _get_abstract_dist_for
abstract_dist = self.preparer.prepare_linked_requirement(
File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 214, in prepare_linked_requirement
abstract_dist.prepare_distribution_metadata(
File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/pip/_internal/distr …
```

fix: remove pin on `pip` version to be latest instead of 19.2.3

---

Formula/aws-sam-cli-nightly.rb
Formula/aws-sam-cli-rc.rb
Formula/aws-sam-cli.rb

Closes #187 
Forked the repo and ran `brew style --fix Formula` from the root. There are a further 9 offences the tool did not auto-fix, but I was hesitant to make any further changes as it already altered more than I expected. The `bottle do` block is the important change, so if the other lint changes are not required I can alter this to just change that block. Running the command on my local tap removes the warnings, but I'm unfamiliar with the changes the tool made so this will probably need further testing.

Run `brew style --fix` to update deprecated syntax

---

bottle-configs/qldbshell.json

This change brings the latest improvements to the QLDB Shell to Homebrew.

Release QLDB Shell v2.0.0-alpha4

---

bottle-configs/qldbshell.json

Update the bottle configs for QLDB Shell v2.0.0-alpha12 release.

Release v2.0.0-alpha12 of the QLDB Shell

---

Formula/k8s-tools.rb

The k8s-tools fails to install unless you manually override the `awscontainertools` binary link. This renames it to avoid name conflict.

chore: update k8s-tools binary to avoid conflicts with container-tools

---

Formula/ec2-metadata-mock.rb

amazon-ec2-metadata-mock darwin/arm64 support

amazon-ec2-metadata-mock darwin/arm64 support

---

Formula/eks-anywhere.rb

Fixes #228
This PR fixes an issue with the eks-anywhere formula under ARM CPU's while we figure out a proper fix. This will install the amd64 version but warn the user that it will not work and the the formula should be uninstalled.

Fix eks-anywhere formula on arm

---

bottle-configs/qldbshell.json

Update the bottle configs for QLDB Shell v2.0.0-alpha14 release.

Release v2.0.0-alpha14 of the QLDB Shell

---

Formula/lightsailctl.rb
bottle-configs/lightsailctl.json

- Update version and sha256 accordingly
- Update the build command to reflect the new location of `main.go`
- Add `with-goproxy-direct` option that lets customers bypass `proxy.golang.org` module proxy
when installing `lightsailctl` from networks where this module proxy is blocked
```sh
$ brew test lightsailctl
==> Testing aws/tap/lightsailctl
==> /usr/local/Cellar/lightsailctl/1.0.2/bin/lightsailctl --plugin --help 2>&1
```

Upgrade to lightsailctl 1.0.2

---

bottle-configs/qldbshell.json

Upgrade qldb shell to v2.0.0

---

Formula/eks-anywhere.rb

Is missing from the upstream eksctl formula so we can add it here.
Adds kubectl to the eks-anywhere dependencies.

Add kubectl dependency

---

Formula/eks-anywhere.rb

Hey, hope you're well. I'm a member of EKS Anywhere, and we just completed our latest release, `v0.7.0`: https://github.com/aws/eks-anywhere/releases/tag/v0.7.0
We'd like to update the AWS homebrew tap to reflect this new release.
Thanks!

chore: update EKS Anywhere homebrew formula to v0.7.0

---

Formula/eks-anywhere.rb

This PR updates the  AWS homebrew tap's EKS Anywhere formula to the latest [release v0.7.2](https://github.com/aws/eks-anywhere/releases/tag/v0.7.2)

chore: update eks anywhere homebrew formula to v0.7.2

---

Formula/eks-anywhere.rb

This PR updates the download links for EKS Anywhere v0.7.2 tarballs for Darwin and Linux.

Fix EKS Anywhere download link for v0.7.2

---

Formula/aws-sam-cli-nightly.rb

https://github.com/aws/aws-sam-cli/issues/3769
`--pre` flag causes some preview dependencies to be installed. This change is targeting to fix it by removing that flag.

fix: remove --pre flag which is causing issues by installing preview dependencies

---

Formula/aws-sam-cli-beta-cdk.rb
Formula/aws-sam-cli-rc.rb

https://github.com/aws/aws-sam-cli/issues/3799
--pre flag causes some preview dependencies to be installed. This change is targeting to fix it by removing that flag.

Removing the --pre flag which causes installation issues

---

bottle-configs/aws-simple-ec2-cli.json

*Issue #, if available:* N/A
Syntax error from manually modifying the JSON file in the previous commit 🤦

Remove extra curly brace that caused parsing error for simple-ec2

---

Formula/cbmc-starter-kit.rb

This changes the python required from 3.9 to 3.8.

cbmc-starter-kit: change python 3.9->3.8

---

Formula/cbmc-viewer.rb

This changes the python required from 3.9 to 3.7 and removes universal-ctags as a dependency.

cbmc-viewer: change python 3.9->3.7, remove universal-ctags

---

Formula/cbmc-viewer.rb

Depending on python@3.7 is a problem on M1.  Doing
```
brew uninstall cbmc-viewer
brew update-reset
brew install cbmc-viewer
```
on M1 generates the error message
```
python@3.7: The x86_64 architecture is required for this software.
Error: cbmc-viewer: An unsatisfied requirement failed this build.
```
One issue may be that there is no M1 bottle for python@3.7 and pip
needs to build 3.7 from scratch on M1.  But this error exists on M1
even with brew python 3.9 installed, so there should be no need for
installing 3.7.  Requiring 3.8 seems to be enough to fix the problem.

Modify cbmc-viewer formula to depend on python@3.8.

---

Formula/ec2-spot-interrupter.rb

*Issue #, if available:* N/A
* Update `spot-interrupter` after releasing [v0.0.8](https://github.com/aws/amazon-ec2-spot-interrupter/releases/tag/v0.0.8)
* Manually updated checksums

update spot-interrupter to v0.0.8

---

bottle-configs/aws-simple-ec2-cli.json

* Add support for launching Spot instances by @GavinBurris42 in https://github.com/awslabs/aws-simple-ec2-cli/pull/85
* Set tags on instance when using a new Launch Template by @snay2 in https://github.com/awslabs/aws-simple-ec2-cli/pull/89
* Capacity type flag by @snay2 in https://github.com/awslabs/aws-simple-ec2-cli/pull/90
**Full Changelog**: https://github.com/awslabs/aws-simple-ec2-cli/compare/v0.8.2...v0.9.0

🥳 simple-ec2 v0.9.0 Automated Release! 🥑

---

bottle-configs/lightsailctl.json

See: <https://github.com/aws/lightsailctl/releases/tag/v1.0.4>
Passes the self test:
```
$ brew test lightsailctl
==> Testing aws/tap/lightsailctl
==> /usr/local/Cellar/lightsailctl/1.0.4/bin/lightsailctl --plugin --help 2>&1
```

Upgrade lightsailctl to 1.0.4

---

Formula/ec2-spot-interrupter.rb

*Issue #, if available:* N/A
Release `v0.0.9` of ec2-spot-interrupter, with these artifacts: https://github.com/aws/amazon-ec2-spot-interrupter/releases/tag/v0.0.9

Publish release v0.0.9 of ec2-spot-interrupter

---

bottle-configs/qldbshell.json

The previous release commit updated the commit SHAs, but failed to bump the QLDB version.

Upgrade qldbshell version to 2.0.2

---

bottle-configs/lightsailctl.json

See: <https://github.com/aws/lightsailctl/releases/tag/v1.0.5>
Passes the self test:
```
$ brew test lightsailctl
Warning: test is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
brew developer off
==> Testing aws/tap/lightsailctl
==> /opt/homebrew/Cellar/lightsailctl/1.0.5/bin/lightsailctl --plugin --help 2>&1
```

Upgrade lightsailctl to 1.0.5

---

Formula/smithy-cli.rb
README.md
bottle-configs/smithy-cli.json

With the publishing of smithy-cli artifacts to GitHub, we'd like to vend the cli through homebrew as well
The smithy repository is under awslabs (for now), and would like to use the official aws tap to vend through homebrew
We will add automation to keep the bottle-config up-to-date with the latest releases in the smithy repo.
*Testing:*
I have tested via brew and confirmed working as expected
```
brew install --build-from-source Formula/smithy-cli.rb --verbose --debug
```

Smithy cli

---

Formula/smithy-cli.rb

Installing smithy-cli on M1 silicon led to gatekeeper preventing the executables from running, 
*Testing:*
Pulled the repo in locally on an M1 mac, ran install (`brew install --build-from-source Formula/smithy-cli.rb --verbose --debug`) without changes, observe that install fails
- check dmesg and see:
```
[510073.159981]: arm64e_plugin_host: running binary "bash" in keys-off mode due to identity: com.apple.bashCODE SIGNING: process 75181[java]: rejecting invalid page at address 0x102574000 from offset 0x0 in file "/opt/homebrew/Cellar/smithy-cli/1.30.0/lib/libjli.dylib" (cs_mtime:1682010630.160538997 == …
```

fix: re-codesign smithy-cli dylibs for apple silicon

---

Formula/smithy-cli.rb

Fix the globs for smithy-cli `post_install` steps for dylibs

fix: constrain smithy-cli dylib globs

---

Formula/smithy-cli.rb

This reverts commit c76362772e08cb18acc8408185fb46c3965a339c.

Revert "fix: constrain smithy-cli dylib globs (#452)"

---

Formula/smithy-cli.rb

Installing via `prefix.install` meant that brew would attempt to symlink all files, and this is problematic in smithy-cli's case because it's a bundled runtime image (and includes everything it needs to run without brew dependencies). 
Files in `libexec` are private to homebrew (meaning it won't try to symlink files to `/usr/local/...`), so we do need to tell it to create a symlink to the smithy executable (which it will add to `/usr/local/bin` as we want).

fix: make smithy-cli lib private, explicitly create bin symlink

---

Formula/cbmc-starter-kit.rb

This commit fixes the checksums for the CBMC starter kit to match the 2.10 tarball (which is the version used since commit b86da88).

Fix cbmc-starter-kit checksums

---

appveyor-sam-cli-nightly.yml

`brew update` is failing due to the error:
```
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
```
Running `brew update-reset` based on https://stackoverflow.com/questions/54834266/error-fetching-usr-local-homebrew-library-taps-homebrew-homebrew-core-failed.

fix: Run brew update-reset for sam-nightly brew bottle build

---

appveyor-sam-cli-nightly.yml

brew bottle build is failing due to an issue while updating homebrew/cask (while running brew update). Based on the suggestions in https://github.com/orgs/Homebrew/discussions/4612, untapping before running `brew update` does not give this error.

fix: Untap homebrew/cask and homebrew/core before running brew update

---

appveyor-sam-cli-nightly.yml

brew untap failed due to existing casks mono-mdk and powershell. Testing if brew untap --force works.

fix: Force untap brew core and cask

---

appveyor-sam-cli-nightly.yml

`brew untap homebrew/cask` worked but `brew untap homebrew/core` gave an error. According to https://github.com/orgs/Homebrew/discussions/4612#discussioncomment-6314857, this env var needs to be unset. I tested this on my machine and it seems to work. According to the [docs](https://docs.brew.sh/Installation) this env var needs to be set for pre-4.0.0 versions to clone core/cask repos.

fix: Unset HOMEBREW_NO_INSTALL_FROM_API env var

---

appveyor-sam-cli-nightly.yml

unsetting the env var does not work on AppVeyor. The brew issue is only happening for cask right now. Added back update-reset which resolved homebrew-core failures and force untap cask.

fix: sam cli nightly remove untap for brew core as it errors out

---

appveyor-sam-cli-nightly.yml

Reverts the changes to sync with aws sam cli yaml file as these changes succeeded  during the prod release https://ci.appveyor.com/project/AWSSAMCLI/homebrew-tap/builds/47483334. 

fix: Revert sam cli nightly brew workarounds as brew has fixed the issues

---

bottle-configs/lightsailctl.json

See: <https://github.com/aws/lightsailctl/releases/tag/v1.0.6>
Passes the self test:
```
$ brew test lightsailctl 
==> Testing aws/tap/lightsailctl
==> /opt/homebrew/Cellar/lightsailctl/1.0.6/bin/lightsailctl --plugin --help 2>&1
```

Upgrade lightsailctl to 1.0.6

---

Formula/aws-sam-cli.rb

Related:
https://github.com/yaml/pyyaml/issues/724
https://github.com/aws/aws-sam-cli/pull/5494
`cython==3.0.0` breaks `PyYAML` when building from source. The change here is to install a lower version of `cython` and install `PyYAML` using that version before installing the rest of the dependencies from AWS SAM CLI.

fix: Added workaround to address cython breaking PyYAML build

---

bottle-configs/aws-sam-cli.json

N/A
Linux configuration has the sha value of `.sig` file where it should be the `.zip` one. This PR fixes that issue.

fix aws-sam-cli linux sha with latest release

---

Formula/aws-sam-cli-nightly.rb

None.
Add `pip` back into the venv for the nightly SAM CLI formula to confirm changes work outside of dev environment.

fix: Add pip back into venv for nightly SAM CLI

---

Formula/aws-sam-cli-nightly.rb
Formula/aws-sam-cli.rb

None.
A recent change in brew caused virtual environments to not include `pip` by default unless an argument was passed into the venv creation method.
This change adds that argument to our call since it defaults to `True`.

fix: Use the without_pip:false argument to include pip in venv

---

Formula/aws-sam-cli-nightly.rb
Formula/aws-sam-cli.rb

N/A
Updates warning message during installation.
Production warning;
```
Warning: On September 12, 2023, AWS will no longer maintain the Homebrew installer for AWS SAM CLI (aws/tap/aws-sam-cli).
For AWS supported installations, use the first-party installers (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html).
To continue using Homebrew, use the community supported installer (https://formulae.brew.sh/formula/aws-sam-cli).
```
Nightly warning;
```
Warning: On September 12, 2023, AWS will no longer maintain Homebrew installer for nightly version of AWS SAM CLI (aws/tap/aws-sam-cli-nightly).
For AWS supported installations, use the first-party installers …
```

fix: update warning messages

---

Formula/_aws-sam-cli-nightly.rb
appveyor-sam-cli-nightly.yml

Related to: https://github.com/aws/homebrew-tap/pull/513
N/A
Brings `aws-sam-cli-nightly` formula back to continue bottle creation during migration period.

fix: bring nightly formula back to fix bottle creation for now

---

Formula/_aws-sam-cli-nightly.rb
Formula/_aws-sam-cli.rb
appveyor-sam-cli-nightly.yml
appveyor.yml
build-formula.sh

Adds temporary solutions to continue building brew bottles for aws-sam-cli until bottle publication jobs have been removed.
- Adds nightly and production formula back with a leading underscore (without underscore, even though with `tap_migrations.json` file) it will still install from this tap, which is not something that we want.
- Adds `-b` option to `build-formula.sh` file to override configuration file during bottle creation (otherwise configuration file is also assumed to start with underscore by default).
- Updated Appveyor definitions with;
- Included `-b` option to override default configuration setting due to formula file name change
- Renames bottle file to remove leading underscore
- Extracts, renames and re-packages `tar.gz` …

fix: add nightly formula back 

---

bottle-configs/amazon-emr-on-eks-custom-image-cli.json

Updated the version to 1.02 for EMR on EKS custom image cli.
Last updated commit: https://github.com/aws/homebrew-tap/pull/314
Tested locally with below command:
```
brew install --build-from-source Formula/emr-on-eks-custom-image.rb
```
and made it running successfully.

 Update EMR on EKS custom image cli to v1.05

---

tap_migrations.json

- When having both the aws and smithy-lang taps tapped, users will run into an issue where they have to fully qualify the brew command with smithy-lang/tap
```
❯ brew upgrade smithy-cli   
==> Downloading https://formulae.brew.sh/api/formula.jws.json
Warning: Formula aws/tap/smithy-cli was renamed to smithy-lang/tap/smithy-cli.
Error: Formulae found in multiple taps:
* smithy-lang/tap/smithy-cli
* smithy-lang/tap/smithy-cli
Please use the fully-qualified name (e.g. smithy-lang/tap/smithy-cli) to refer to a specific formula.
```
- Removing this entry means this problem will go away
- I did not remove the README entry about the formula being migrated, since it is still valid
- Note: even untapping smithy-lang and keeping aws still renders the error - I'm not sure …

Remove smithy-cli from tap_migrations.json

---

Formula/eksctl.rb
Formula/eksdemo.rb

Both the packages are stale! 
- eksdemo should be v0.18.2 ( https://github.com/awslabs/eksdemo/releases/tag/v0.18.2 )
- eksctl should be v0.204.0 ( https://github.com/eksctl-io/eksctl/releases/tag/v0.204.0 )

Update to latest releases of eksdemo(v0.18.2) and eksctl(v0.204.0)

---

Formula/eksctl.rb

We have a new eksctl release: https://github.com/eksctl-io/eksctl/releases/tag/v0.205.0

Update eksctl to 2.0.5

---

Formula/cbmc-viewer.rb

This reverts commit 1b2a38f6abd4b23ce2cbed1e1239025b80e457d5, which introduced an incomplete update (the bottles still point to viewer-3.10).

Revert "cbmc-viewer"
